import { inputTypeEnum } from '../../../../../enum/input_type';
import { versionAvailable } from '../../../../../enum/version';
import { MapperSeeder } from '../../../../../model/mapper';

const group_name = 'AGR';

export const AGR: MapperSeeder[] = [
  {
    description: 'Record Prefix',
    field: 'record_prefix',
    start_char: 1,
    size: 19,
    end_char: 20,
    input_type: inputTypeEnum.Alpha,
    is_required: true,
    tag: 'free_text',
    version: versionAvailable.v21,
    group_name,
  },
  {
    description: 'Submitter Agreement Number',
    field: 'submitter_agreement_number',
    start_char: 20,
    size: 14,
    end_char: 34,
    input_type: inputTypeEnum.Alpha,
    is_required: true,
    tag: 'free_text',
    version: versionAvailable.v21,
    group_name,
  },
  {
    description: 'International Standard Agreement Code',
    field: 'international_standard_agreement_code',
    start_char: 34,
    size: 14,
    end_char: 48,
    input_type: inputTypeEnum.Alpha,
    is_required: false,
    tag: 'free_text',
    version: versionAvailable.v21,
    group_name,
  },
  {
    description: 'Agreement Type',
    field: 'agreement_type',
    start_char: 48,
    size: 2,
    end_char: 50,
    input_type: inputTypeEnum.Lookup,
    is_required: true,
    tag: 'free_text',
    version: versionAvailable.v21,
    group_name,
  },
  {
    description: 'Agreement Start Date',
    field: 'agreement_start_date',
    start_char: 50,
    size: 8,
    end_char: 58,
    input_type: inputTypeEnum.Date,
    is_required: true,
    tag: 'free_text_date',
    version: versionAvailable.v21,
    group_name,
  },
  {
    description: 'Agreement End Date',
    field: 'agreement_end_date',
    start_char: 58,
    size: 8,
    end_char: 66,
    input_type: inputTypeEnum.Date,
    is_required: false,
    tag: 'free_text_date',
    version: versionAvailable.v21,
    group_name,
  },
  {
    description: 'Retention End Date',
    field: 'retention_end_date',
    start_char: 66,
    size: 8,
    end_char: 74,
    input_type: inputTypeEnum.Date,
    is_required: false,
    tag: 'free_text_date',
    version: versionAvailable.v21,
    group_name,
  },
  {
    description: 'Prior Royalty Status',
    field: 'prior_royalty_status',
    start_char: 74,
    size: 1,
    end_char: 75,
    input_type: inputTypeEnum.Alpha,
    is_required: true,
    tag: 'free_text',
    version: versionAvailable.v21,
    group_name,
  },
  {
    description: 'Prior Royalty Start Date',
    field: 'prior_royalty_start_date',
    start_char: 75,
    size: 8,
    end_char: 83,
    input_type: inputTypeEnum.Date,
    is_required: false,
    tag: 'free_text_date',
    version: versionAvailable.v21,
    group_name,
  },
  {
    description: 'Post-term Collection Status',
    field: 'post_term_collection_status',
    start_char: 83,
    size: 1,
    end_char: 84,
    input_type: inputTypeEnum.Alpha,
    is_required: true,
    tag: 'free_text',
    version: versionAvailable.v21,
    group_name,
  },
  {
    description: 'Post-term Collection End Date',
    field: 'post_term_collection_end_date',
    start_char: 84,
    size: 8,
    end_char: 92,
    input_type: inputTypeEnum.Date,
    is_required: false,
    tag: 'free_text_date',
    version: versionAvailable.v21,
    group_name,
  },
  {
    description: 'Date of Signature of Agreement',
    field: 'date_of_signature_of_agreement',
    start_char: 92,
    size: 8,
    end_char: 100,
    input_type: inputTypeEnum.Date,
    is_required: false,
    tag: 'free_text_date',
    version: versionAvailable.v21,
    group_name,
  },
  {
    description: 'Number of Works',
    field: 'number_of_works',
    start_char: 100,
    size: 5,
    end_char: 105,
    input_type: inputTypeEnum.Numeric,
    is_required: true,
    tag: 'free_text',
    version: versionAvailable.v21,
    group_name,
  },
  {
    description: 'Sales/Manufacture Clause',
    field: 'sales_manufacture_clause',
    start_char: 105,
    size: 1,
    end_char: 106,
    input_type: inputTypeEnum.Lookup,
    is_required: false,
    tag: 'free_text',
    version: versionAvailable.v21,
    group_name,
  },
  {
    description: 'Shares change',
    field: 'shares_change',
    start_char: 106,
    size: 1,
    end_char: 107,
    input_type: inputTypeEnum.Boolean,
    is_required: false,
    tag: 'free_text',
    version: versionAvailable.v21,
    group_name,
  },
  {
    description: 'Advance Given',
    field: 'advance_given',
    start_char: 107,
    size: 1,
    end_char: 108,
    input_type: inputTypeEnum.Boolean,
    is_required: false,
    tag: 'free_text',
    version: versionAvailable.v21,
    group_name,
  },
  {
    description: 'Society-assigned Agreement Number',
    field: 'society_assigned_agreement_number',
    start_char: 108,
    size: 14,
    end_char: 122,
    input_type: inputTypeEnum.Alpha,
    is_required: false  ,
    tag: 'free_text',
    version: versionAvailable.v21,
    group_name,
  },
];
