version: "3"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=portamento_cwr
    ports:
      - 3306:3306
  portamento_cwr:
    build:
      context: "."
      args:
        ENV: development
    environment:
      - PORT
      - SECRET=secret
      - NORM_ADAPTER=mysql
      - NORM_MYSQL_HOST=mysql
      - NORM_MYSQL_USER=portamento_cwr
      - NORM_MYSQL_PASSWORD
      - NORM_MYSQL_DATABASE=portamento_cwr
    volumes:
      - ".:/app"
    ports:
      - 3020:3020
    command: [ "npm", "run", "dev" ]
    depends_on:
      - mysql
