import { controlRecordEnum } from '../../enum/control_record';
import { inputTypeEnum } from '../../enum/input_type';
import { versionAvailable } from '../../enum/version';
import { MapperSeeder } from '../../model/mapper';

const HDR: MapperSeeder[] = [
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.HDR,
    input_type: inputTypeEnum.Alpha,
    is_required: true,
    tag: 'free_text',
    start_char: 1,
    end_char: 4,
    size: 3,
    field: 'record_type',
    description: 'Record Type',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.HDR,
    input_type: inputTypeEnum.Lookup,
    is_required: true,
    tag: 'free_text',
    start_char: 4,
    end_char: 6,
    size: 2,
    field: 'sender_type',
    description: 'Sender Type',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.HDR,
    input_type: inputTypeEnum.Numeric,
    is_required: true,
    tag: 'free_text',
    start_char: 6,
    end_char: 15,
    size: 9,
    field: 'sender_id',
    description: 'Sender ID',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.HDR,
    input_type: inputTypeEnum.AlphaNumeric,
    is_required: true,
    tag: 'free_text',
    start_char: 15,
    end_char: 60,
    size: 45,
    field: 'sender_name',
    description: 'Sender Name',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.HDR,
    input_type: inputTypeEnum.AlphaNumeric,
    is_required: true,
    tag: 'free_text',
    start_char: 60,
    end_char: 65,
    size: 5,
    field: 'edi_standard_version_number',
    description: 'EDI Standard Version Number',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.HDR,
    input_type: inputTypeEnum.Date,
    is_required: true,
    tag: 'free_text_date',
    start_char: 65,
    end_char: 73,
    size: 8,
    field: 'creation_date',
    description: 'Creation Date',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.HDR,
    input_type: inputTypeEnum.Time,
    is_required: true,
    tag: 'free_text_time',
    start_char: 73,
    end_char: 79,
    size: 6,
    field: 'creation_time',
    description: 'Creation Time',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.HDR,
    input_type: inputTypeEnum.Date,
    is_required: true,
    tag: 'free_text_date',
    start_char: 79,
    end_char: 87,
    size: 8,
    field: 'transmission_date',
    description: 'Transmission Date',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.HDR,
    input_type: inputTypeEnum.Lookup,
    is_required: false,
    tag: 'free_text',
    start_char: 87,
    end_char: 102,
    size: 15,
    field: 'character_set',
    description: 'Character Set',
  },
];

const GRH: MapperSeeder[] = [
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.GRH,
    input_type: inputTypeEnum.AlphaNumeric,
    is_required: true,
    tag: 'free_text',
    start_char: 1,
    end_char: 4,
    size: 3,
    field: 'record_type',
    description: 'Record Type',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.GRH,
    input_type: inputTypeEnum.Lookup,
    is_required: true,
    tag: 'free_text',
    start_char: 4,
    end_char: 7,
    size: 3,
    field: 'transaction_type',
    description: 'Transaction Type',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.GRH,
    input_type: inputTypeEnum.Numeric,
    is_required: true,
    tag: 'free_text',
    start_char: 7,
    end_char: 12,
    size: 5,
    field: 'type_group_id',
    description: 'Type Group ID',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.GRH,
    input_type: inputTypeEnum.AlphaNumeric,
    is_required: true,
    tag: 'free_text',
    start_char: 12,
    end_char: 17,
    size: 5,
    field: 'version_number_for_this_transaction_type',
    description: 'Version Number for this transaction type',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.GRH,
    input_type: inputTypeEnum.Numeric,
    is_required: false,
    tag: 'free_text',
    start_char: 17,
    end_char: 27,
    size: 10,
    field: 'batch_request',
    description: 'Batch Request',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.GRH,
    input_type: inputTypeEnum.Lookup,
    is_required: false,
    tag: 'free_text',
    start_char: 27,
    end_char: 29,
    size: 2,
    field: 'submission_or_distribution_type',
    description: 'Submission / Distribution type',
  },
];

const GRT: MapperSeeder[] = [
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.GRT,
    input_type: 'lookup',
    is_required: true,
    tag: 'free_text',
    start_char: 1,
    end_char: 4,
    size: 3,
    field: 'record_type',
    description: 'Record Type',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.GRT,
    input_type: 'numeric',
    is_required: true,
    tag: 'free_text',
    start_char: 4,
    end_char: 9,
    size: 5,
    field: 'group_id',
    description: 'Group ID',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.GRT,
    input_type: 'numeric',
    is_required: true,
    tag: 'free_text',
    start_char: 9,
    end_char: 17,
    size: 8,
    field: 'transaction_count',
    description: 'Transaction Count',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.GRT,
    input_type: 'numeric',
    is_required: true,
    tag: 'free_text',
    start_char: 17,
    end_char: 25,
    size: 8,
    field: 'record_count',
    description: 'Record Count',
  },
];

const TRL: MapperSeeder[] = [
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.TRL,
    input_type: 'lookup',
    is_required: true,
    tag: 'free_text',
    start_char: 1,
    end_char: 4,
    size: 3,
    field: 'record_type',
    description: 'Record Type',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.TRL,
    input_type: 'numeric',
    is_required: true,
    tag: 'free_text',
    start_char: 4,
    end_char: 9,
    size: 5,
    field: 'group_count',
    description: 'Group Count',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.TRL,
    input_type: 'numeric',
    is_required: true,
    tag: 'free_text',
    start_char: 9,
    end_char: 17,
    size: 8,
    field: 'transaction_count',
    description: 'Transaction Count',
  },
  {
    version: versionAvailable.v21,
    group_name: controlRecordEnum.TRL,
    input_type: 'numeric',
    is_required: true,
    tag: 'free_text',
    start_char: 17,
    end_char: 25,
    size: 8,
    field: 'record_count',
    description: 'Record Count',
  },
];

export const cwr21: MapperSeeder[] = [...HDR, ...GRH, ...GRT, ...TRL];
