import { inputTypeEnum } from '../../../../../enum/input_type';
import { versionAvailable } from '../../../../../enum/version';
import { MapperSeeder } from '../../../../../model/mapper';

const group_name = 'FTV';
const version = versionAvailable.v300;

export const FTV: MapperSeeder[] = [
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 1,
    size: 19,
    end_char: 20,
    field: 'record_prefix',
    description: 'Record Prefix',
    is_required: true,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 20,
    size: 3,
    end_char: 23,
    field: 'intended_purpose',
    description: 'Intended Purpose',
    is_required: true,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 23,
    size: 60,
    end_char: 83,
    field: 'production_title',
    description: 'Production Title',
    is_required: true,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 83,
    size: 12,
    end_char: 95,
    field: 'production_number',
    description: 'Production Number',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 95,
    size: 60,
    end_char: 155,
    field: 'episode_title',
    description: 'Episode Title',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 155,
    size: 20,
    end_char: 175,
    field: 'episode_number',
    description: 'Episode Number',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Numeric,
    tag: 'free_text',
    start_char: 175,
    size: 4,
    end_char: 179,
    field: 'year_of_production',
    description: 'Year of Production',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 179,
    size: 0,
    end_char: 179,
    field: 'avi_key',
    description: 'AVI Key',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 179,
    size: 4,
    end_char: 183,
    field: 'avi_society_code',
    description: 'AVI Society Code',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 183,
    size: 15,
    end_char: 198,
    field: 'audio_visual_number',
    description: 'Audio-Visual Number',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 198,
    size: 0,
    end_char: 198,
    field: 'v_isan',
    description: 'V-ISAN',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 198,
    size: 12,
    end_char: 210,
    field: 'isan',
    description: 'ISAN',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 210,
    size: 4,
    end_char: 214,
    field: 'episode',
    description: 'Episode',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 214,
    size: 1,
    end_char: 215,
    field: 'check_digit_1',
    description: 'Check Digit 1',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 215,
    size: 8,
    end_char: 223,
    field: 'Version',
    description: 'Version',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 223,
    size: 1,
    end_char: 224,
    field: 'check_digit_2',
    description: 'Check Digit 2',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 224,
    size: 0,
    end_char: 224,
    field: 'eidr_head',
    description: 'EIDR Head',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 224,
    size: 20,
    end_char: 244,
    field: 'eidr',
    description: 'EIDR',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 244,
    size: 1,
    end_char: 245,
    field: 'check_digit',
    description: 'Check Digit',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 245,
    size: 40,
    end_char: 285,
    field: 'version',
    description: 'Version Name',
    is_required: false,
  },
];
