import { inputTypeEnum } from '../../../../../enum/input_type';
import { versionAvailable } from '../../../../../enum/version';
import { MapperSeeder } from '../../../../../model/mapper';

const group_name = 'NPR';
const version = versionAvailable.v300;

export const NPR: MapperSeeder[] = [
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 1,
    size: 19,
    end_char: 20,
    field: 'record_prefix',
    description: 'Record Prefix',
    is_required: true,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 20,
    size: 160,
    end_char: 180,
    field: 'performing_artist_name',
    description: 'Performing Artist Name',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 180,
    size: 160,
    end_char: 340,
    field: 'performing_artist_first_name',
    description: 'Performing Artist First Name',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 340,
    size: 11,
    end_char: 351,
    field: 'performing_artist_ip_name_number',
    description: 'Performing Artist IPI Name Number',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 351,
    size: 16,
    end_char: 367,
    field: 'international_standard_name_identifier',
    description: 'International Standard Name Identifier',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 367,
    size: 2,
    end_char: 369,
    field: 'performance_language',
    description: 'Performance Language',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 369,
    size: 3,
    end_char: 372,
    field: 'performance_dialect',
    description: 'Performance Dialect',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 372,
    size: 2,
    end_char: 374,
    field: 'language_code',
    description: 'Language Code',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 374,
    size: 4,
    end_char: 378,
    field: 'script_code',
    description: 'Script Code',
    is_required: false,
  },
];
