import { inputTypeEnum } from '../../../../../enum/input_type';
import { versionAvailable } from '../../../../../enum/version';
import { MapperSeeder } from '../../../../../model/mapper';

const group_name = 'SPU';
const version = versionAvailable.v300;

export const SPU: MapperSeeder[] = [
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 1,
    size: 19,
    end_char: 20,
    field: 'record_prefix',
    description: 'Record Prefix',
    is_required: true,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Numeric,
    tag: 'free_text',
    start_char: 20,
    size: 2,
    end_char: 22,
    field: 'publisher_sequence_number',
    description: 'Publisher Sequence Number',
    is_required: true,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 22,
    size: 9,
    end_char: 31,
    field: 'interested_party_number',
    description: 'Interested Party Number',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 31,
    size: 45,
    end_char: 76,
    field: 'publisher_name',
    description: 'Publisher Name',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Flag,
    tag: 'free_text',
    start_char: 76,
    size: 1,
    end_char: 77,
    field: 'publisher_unknown_indicator',
    description: 'Publisher Unknown Indicator',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 77,
    size: 2,
    end_char: 79,
    field: 'publisher_role',
    description: 'Publisher Role',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 79,
    size: 11,
    end_char: 90,
    field: 'publisher_ipi_name',
    description: 'Publisher IPI Name #',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 90,
    size: 13,
    end_char: 103,
    field: 'publisher_ipi_base_number',
    description: 'Publisher IPI Base Number',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 103,
    size: 1,
    end_char: 104,
    field: 'usa_license_ind',
    description: 'USA License Ind',
    is_required: false,
  },
];
