import { inputTypeEnum } from '../../../../../enum/input_type';
import { versionAvailable } from '../../../../../enum/version';
import { MapperSeeder } from '../../../../../model/mapper';

const group_name = 'SWR';
const version = versionAvailable.v300;

export const SWR: MapperSeeder[] = [
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 1,
    size: 19,
    end_char: 20,
    field: 'record_prefix',
    description: 'Record Prefix',
    is_required: true,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 20,
    size: 9,
    end_char: 29,
    field: 'interested_party_number',
    description: 'Interested Party Number',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 29,
    size: 45,
    end_char: 74,
    field: 'writer_last_name',
    description: 'Writer Last Name',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 74,
    size: 30,
    end_char: 104,
    field: 'writer_first_name',
    description: 'Writer First Name',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Flag,
    tag: 'free_text',
    start_char: 104,
    size: 1,
    end_char: 105,
    field: 'writer_unknown_indicator',
    description: 'Writer Unknown Indicator',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 105,
    size: 2,
    end_char: 107,
    field: 'writer_role',
    description: 'Writer Role',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 107,
    size: 11,
    end_char: 118,
    field: 'writer_ipi_name_number',
    description: 'Writer IPI Name Number',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 118,
    size: 13,
    end_char: 131,
    field: 'writer_ipi_base_number',
    description: 'Writer IPI Base Number',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Flag,
    tag: 'free_text',
    start_char: 131,
    size: 1,
    end_char: 132,
    field: 'reversionary_indicator',
    description: 'Reversionary Indicator',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Boolean,
    tag: 'free_text',
    start_char: 132,
    size: 1,
    end_char: 133,
    field: 'first_recording_refusal_ind',
    description: 'First Recording Refusal Ind',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Boolean,
    tag: 'free_text',
    start_char: 133,
    size: 1,
    end_char: 134,
    field: 'work_for_hire_indicator',
    description: 'Work For Hire Indicator',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 134,
    size: 1,
    end_char: 135,
    field: 'usa_license_indicator',
    description: 'USA License Indicator',
    is_required: false,
  },
];
