import { inputTypeEnum } from '../../../../../enum/input_type';
import { versionAvailable } from '../../../../../enum/version';
import { MapperSeeder } from '../../../../../model/mapper';

const group_name = 'WRI';
const version = versionAvailable.v300;

export const WRI: Array<MapperSeeder> = [
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 1,
    size: 19,
    end_char: 20,
    field: 'record_prefix',
    description: 'Record Prefix',
    is_required: true,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 20,
    size: 14,
    end_char: 34,
    field: 'submitter_work_number',
    description: 'Submitter Work Number',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Standard,
    tag: 'free_text',
    start_char: 34,
    size: 11,
    end_char: 45,
    field: 'writer_ipi_name_number',
    description: 'Writer IPI Name Number',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 45,
    size: 45,
    end_char: 90,
    field: 'writer_last_name',
    description: 'Writer Last Name',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 90,
    size: 45,
    end_char: 135,
    field: 'writer_first_name',
    description: 'Writer First Name',
    is_required: false,
  },
  {
    version,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 135,
    size: 2,
    end_char: 137,
    field: 'writer_role_code',
    description: 'Writer Role Code',
    is_required: false,
  },
];
