import { inputTypeEnum } from '../../../../../enum/input_type';
import { versionAvailable } from '../../../../../enum/version';
import { MapperSeeder } from '../../../../../model/mapper';

const group_name = 'ISA';

export const ISA: MapperSeeder[] = [
  {
    description: 'Record Prefix',
    field: 'record_prefix',
    start_char: 1,
    size: 19,
    end_char: 20,
    input_type: inputTypeEnum.Alpha,
    is_required: true,
    tag: 'free_text',
    version: versionAvailable.v300,
    group_name,
  },
  {
    description: 'Creation Date',
    field: 'creation_date',
    start_char: 20,
    size: 8,
    end_char: 28,
    input_type: inputTypeEnum.Date,
    is_required: true,
    tag: 'free_text',
    version: versionAvailable.v300,
    group_name,
  },
  {
    description: 'Creation Time',
    field: 'creation_time',
    start_char: 28,
    size: 6,
    end_char: 34,
    input_type: inputTypeEnum.Time,
    is_required: true,
    tag: 'free_text',
    version: versionAvailable.v300,
    group_name,
  },
  {
    description: 'Original Group ID',
    field: 'original_group_id',
    start_char: 34,
    size: 5,
    end_char: 39,
    input_type: inputTypeEnum.Numeric,
    is_required: true,
    tag: 'free_text',
    version: versionAvailable.v300,
    group_name,
  },
  {
    description: 'Original Transaction Sequence Number',
    field: 'original_transaction_sequence_number',
    start_char: 39,
    size: 8,
    end_char: 47,
    input_type: inputTypeEnum.Numeric,
    is_required: true,
    tag: 'free_text',
    version: versionAvailable.v300,
    group_name,
  },
  {
    description: 'Original Transaction Type',
    field: 'original_transaction_type',
    start_char: 47,
    size: 3,
    end_char: 50,
    input_type: inputTypeEnum.Lookup,
    is_required: true,
    tag: 'free_text',
    version: versionAvailable.v300,
    group_name,
  },
  {
    description: 'Creation Title',
    field: 'creation_title',
    start_char: 50,
    size: 60,
    end_char: 110,
    input_type: inputTypeEnum.Alpha,
    is_required: false,
    tag: 'free_text',
    version: versionAvailable.v300,
    group_name,
  },
  {
    description: 'Language Code',
    field: 'language_code',
    start_char: 110,
    size: 2,
    end_char: 112,
    input_type: inputTypeEnum.Standard,
    is_required: false,
    tag: 'free_text',
    version: versionAvailable.v300,
    group_name,
  },
  {
    description: 'Submitter Work Number',
    field: 'submitter_work_number',
    start_char: 112,
    size: 14,
    end_char: 126,
    input_type: inputTypeEnum.Alpha,
    is_required: true,
    tag: 'free_text',
    version: versionAvailable.v300,
    group_name,
  },
  {
    description: 'Processing Date',
    field: 'processing_date',
    start_char: 126,
    size: 8,
    end_char: 134,
    input_type: inputTypeEnum.Date,
    is_required: true,
    tag: 'free_text',
    version: versionAvailable.v300,
    group_name,
  },
  {
    description: 'ISWC',
    field: 'iswc',
    start_char: 134,
    size: 11,
    end_char: 145,
    input_type: inputTypeEnum.Standard,
    is_required: true,
    tag: 'free_text',
    version: versionAvailable.v300,
    group_name,
  },
  {
    description: 'ISWC Preferred Indicator',
    field: 'iswc_preferred_indicator',
    start_char: 145,
    size: 1,
    end_char: 146,
    input_type: inputTypeEnum.Alpha,
    is_required: true,
    tag: 'free_text',
    version: versionAvailable.v300,
    group_name,
  },
  {
    description: 'Transaction Status',
    field: 'transaction_status',
    start_char: 146,
    size: 2,
    end_char: 148,
    input_type: inputTypeEnum.Lookup,
    is_required: true,
    tag: 'free_text',
    version: versionAvailable.v300,
    group_name,
  },
];
