import { inputTypeEnum } from '../../../../../enum/input_type';
import { versionAvailable } from '../../../../../enum/version';
import { MapperSeeder } from '../../../../../model/mapper';

const group_name = 'COM';

export const COM: Array<MapperSeeder> = [
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 1,
    size: 19,
    end_char: 20,
    field: 'record_prefix',
    description: 'Record Prefix',
    is_required: true,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 20,
    size: 60,
    end_char: 80,
    field: 'title',
    description: 'Title',
    is_required: true,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 80,
    size: 11,
    end_char: 91,
    field: 'iswc_of_component',
    description: 'ISWC of Component',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 91,
    size: 14,
    end_char: 105,
    field: 'submitter_work',
    description: 'Submitter Work #',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Time,
    tag: 'free_text',
    start_char: 105,
    size: 6,
    end_char: 111,
    field: 'duration',
    description: 'Duration',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 111,
    size: 45,
    end_char: 156,
    field: 'writer_1_last_name',
    description: 'Writer 1 Last Name',
    is_required: true,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 156,
    size: 30,
    end_char: 186,
    field: 'writer_1_first_name',
    description: 'Writer 1 First Name',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 186,
    size: 11,
    end_char: 197,
    field: 'writer_1_ipi_name',
    description: 'Writer 1 IPI Name #',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 197,
    size: 45,
    end_char: 242,
    field: 'writer_2_last_name',
    description: 'Writer 2 Last Name',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 242,
    size: 30,
    end_char: 272,
    field: 'writer_2_first_name',
    description: 'Writer 2 First Name',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 272,
    size: 11,
    end_char: 283,
    field: 'writer_2_ipi_name',
    description: 'Writer 2 IPI Name #',
    is_required: false,
  },
];
