import { inputTypeEnum } from '../../../../../enum/input_type';
import { versionAvailable } from '../../../../../enum/version';
import { MapperSeeder } from '../../../../../model/mapper';

const group_name = 'NPR';

export const NPR: Array<MapperSeeder> = [
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 1,
    size: 19,
    end_char: 20,
    field: 'record_prefix',
    description: 'Record Prefix',
    is_required: true,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 20,
    size: 160,
    end_char: 180,
    field: 'performing_artist_name',
    description: 'Performing Artist Name',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 180,
    size: 160,
    end_char: 340,
    field: 'performing_artist_first_name',
    description: 'Performing Artist First Name',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 340,
    size: 11,
    end_char: 351,
    field: 'performing_artist_ip_name',
    description: 'Performing Artist IPI Name #',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 351,
    size: 13,
    end_char: 364,
    field: 'performing_artist_ipi_base_number',
    description: 'Performing Artist IPI Base Number',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 364,
    size: 2,
    end_char: 366,
    field: 'language_code',
    description: 'Language Code',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 366,
    size: 2,
    end_char: 368,
    field: 'performance_language',
    description: 'Performance Language',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 368,
    size: 3,
    end_char: 371,
    field: 'performance_dialect',
    description: 'Performance Dialect',
    is_required: false,
  },
];
