import { inputTypeEnum } from '../../../../../enum/input_type';
import { versionAvailable } from '../../../../../enum/version';
import { MapperSeeder } from '../../../../../model/mapper';

const group_name = 'ORN';

export const ORN: Array<MapperSeeder> = [
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 1,
    size: 19,
    end_char: 20,
    field: 'record_prefix',
    description: 'Record Prefix',
    is_required: true,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 20,
    size: 3,
    end_char: 23,
    field: 'intended_purpose',
    description: 'Intended Purpose',
    is_required: true,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 23,
    size: 60,
    end_char: 83,
    field: 'production_title',
    description: 'Production Title',
    is_required: true,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 83,
    size: 15,
    end_char: 98,
    field: 'cd_identifier',
    description: 'CD Identifier',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Numeric,
    tag: 'free_text',
    start_char: 98,
    size: 4,
    end_char: 102,
    field: 'cut_number',
    description: 'Cut Number',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 102,
    size: 60,
    end_char: 162,
    field: 'library',
    description: 'Library',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 162,
    size: 1,
    end_char: 163,
    field: 'bltvr',
    description: 'BLTVR',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 163,
    size: 0,
    end_char: 163,
    field: 'v_isan',
    description: 'V-ISAN',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Numeric,
    tag: 'free_text',
    start_char: 163,
    size: 8,
    end_char: 171,
    field: 'version',
    description: 'Version',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Numeric,
    tag: 'free_text',
    start_char: 171,
    size: 12,
    end_char: 183,
    field: 'isan',
    description: 'ISAN',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Numeric,
    tag: 'free_text',
    start_char: 183,
    size: 4,
    end_char: 187,
    field: 'episode',
    description: 'Episode',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Numeric,
    tag: 'free_text',
    start_char: 187,
    size: 1,
    end_char: 188,
    field: 'check_digit',
    description: 'Check Digit',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 188,
    size: 12,
    end_char: 200,
    field: 'production',
    description: 'Production',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 200,
    size: 60,
    end_char: 260,
    field: 'episode_title',
    description: 'Episode Title',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 200,
    size: 20,
    end_char: 280,
    field: 'episode_number',
    description: 'Episode #',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Numeric,
    tag: 'free_text',
    start_char: 280,
    size: 4,
    end_char: 284,
    field: 'year_of_production',
    description: 'Year of Production',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Numeric,
    tag: 'free_text',
    start_char: 284,
    size: 0,
    end_char: 284,
    field: 'avi_key',
    description: 'AVI Key',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Numeric,
    tag: 'free_text',
    start_char: 284,
    size: 3,
    end_char: 287,
    field: 'avi_society_code',
    description: 'AVI Society Code',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 287,
    size: 15,
    end_char: 302,
    field: 'audio_visual_number',
    description: 'Audio-Visual Number',
    is_required: false,
  },
];
