import { inputTypeEnum } from '../../../../../enum/input_type';
import { versionAvailable } from '../../../../../enum/version';
import { MapperSeeder } from '../../../../../model/mapper';

const group_name = 'REC';

export const REC: Array<MapperSeeder> = [
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 1,
    size: 19,
    end_char: 20,
    field: 'record_prefix',
    description: 'Record Prefix',
    is_required: true,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Date,
    tag: 'free_text_date',
    start_char: 20,
    size: 8,
    end_char: 28,
    field: 'first_release_date',
    description: 'First Release Date',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 28,
    size: 60,
    end_char: 88,
    field: 'constant',
    description: 'Constant',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Time,
    tag: 'free_text',
    start_char: 88,
    size: 6,
    end_char: 94,
    field: 'first_release_duration',
    description: 'First Release Duration',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 94,
    size: 5,
    end_char: 99,
    field: 'constant',
    description: 'Constant',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 99,
    size: 60,
    end_char: 159,
    field: 'first_album_title',
    description: 'First Album Title',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 159,
    size: 60,
    end_char: 219,
    field: 'first_album_label',
    description: 'First Album Label',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Alpha,
    tag: 'free_text',
    start_char: 219,
    size: 18,
    end_char: 237,
    field: 'first_release_catalog',
    description: 'First Release Catalog #',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 237,
    size: 13,
    end_char: 250,
    field: 'ean',
    description: 'EAN',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 250,
    size: 12,
    end_char: 262,
    field: 'isrc',
    description: 'ISRC',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 262,
    size: 1,
    end_char: 263,
    field: 'recording_format',
    description: 'Recording Format',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 263,
    size: 1,
    end_char: 264,
    field: 'recording_technique',
    description: 'Recording Technique',
    is_required: false,
  },
  {
    version: versionAvailable.v21,
    group_name,
    input_type: inputTypeEnum.Lookup,
    tag: 'free_text',
    start_char: 264,
    size: 3,
    end_char: 267,
    field: 'media_type',
    description: 'Media Type',
    is_required: false,
  },
];
