import { LookUpSeeder } from '../model/lookup';
import { Options } from '../model/model';

const optionSenderTypes: Array<Options> = [
  {
    tag: 'PB',
    name: 'Publisher',
  },
  {
    tag: 'SO',
    name: 'Society',
  },
  {
    tag: 'AA',
    name: 'Administrative Agency',
  },
  {
    tag: 'WR',
    name: 'Writer',
  },
];

const optionGrhTransactionTypes: Array<Options> = [
  {
    tag: 'AGR',
    name: 'Agreement supporting Work Registration',
  },
  {
    tag: 'NWR',
    name: 'New Works Registration',
  },
  {
    tag: 'REV',
    name: 'Revised Registration',
  },
  {
    tag: 'ISW',
    name: 'Notification of ISWC assigned to a work',
  },
  {
    tag: 'EXC',
    name: 'Existing work which is in conflict with a work registration',
  },

  {
    tag: 'ACK',
    name: 'Acknowledgment of Transaction',
  },
];

export const lookup: Array<LookUpSeeder> = [
  {
    version: '21',
    line: '1',
    group_name: 'HDR',
    input_type: 'alpha',
    is_required: true,
    tag: 'HDR',
    start_char: 1,
    end_char: 3,
    size: 3,
    field: 'Record Type',
    description: 'Transmission Header',
  },
  {
    version: '21',
    line: '1',
    group_name: 'HDR',
    input_type: 'alpha',
    is_required: true,
    tag: 'options',
    start_char: 4,
    end_char: 5,
    size: 2,
    field: 'Sender Type',
    options: JSON.stringify(optionSenderTypes),
    description: 'Transmission Header',
  },
  {
    version: '21',
    line: '1',
    group_name: 'HDR',
    input_type: 'numeric',
    is_required: true,
    tag: 'free_text',
    start_char: 6,
    end_char: 14,
    size: 9,
    field: 'Sender ID',
    description: 'Transmission Header',
  },
  {
    version: '21',
    line: '1',
    group_name: 'HDR',
    input_type: 'alpha',
    is_required: true,
    tag: 'free_text',
    start_char: 15,
    end_char: 59,
    size: 45,
    field: 'Sender Name',
    description: 'Transmission Header',
  },
  {
    version: '21',
    line: '1',
    group_name: 'HDR',
    input_type: 'alpha',
    is_required: true,
    tag: 'free_text',
    start_char: 60,
    end_char: 64,
    size: 5,
    field: 'EDI Standard Version Number',
    description: 'Transmission Header',
  },
  {
    version: '21',
    line: '1',
    group_name: 'HDR',
    input_type: 'date',
    is_required: true,
    tag: 'free_text_date',
    start_char: 65,
    end_char: 72,
    size: 8,
    field: 'Creation Date',
    description: 'Transmission Header',
  },
  {
    version: '21',
    line: '1',
    group_name: 'HDR',
    input_type: 'time',
    is_required: true,
    tag: 'free_text_time',
    start_char: 73,
    end_char: 78,
    size: 6,
    field: 'Creation Time',
    description: 'Transmission Header',
  },
  {
    version: '21',
    line: '1',
    group_name: 'HDR',
    input_type: 'date',
    is_required: true,
    tag: 'free_text_date',
    start_char: 79,
    end_char: 86,
    size: 8,
    field: 'Transmision Date',
    description: 'Transmission Header',
  },
  {
    version: '21',
    line: '1',
    group_name: 'HDR',
    input_type: 'lookup',
    is_required: false,
    tag: 'free_text',
    start_char: 87,
    end_char: 101,
    size: 15,
    field: 'Character Set',
    description: 'Transmission Header',
  },

  {
    version: '21',
    line: '2',
    group_name: 'GRH',
    input_type: 'alpha',
    is_required: true,
    tag: 'GRH',
    start_char: 1,
    end_char: 3,
    size: 3,
    field: 'Record Type',
    description: 'Group Header',
  },
  {
    version: '21',
    line: '2',
    group_name: 'GRH',
    input_type: 'alpha',
    is_required: true,
    tag: 'options',
    start_char: 4,
    end_char: 6,
    size: 3,
    field: 'Transaction Type',
    options: JSON.stringify(optionGrhTransactionTypes),
    description: 'Group Header',
  },
  {
    version: '21',
    line: '2',
    group_name: 'GRH',
    input_type: 'numeric',
    is_required: true,
    tag: 'free_text',
    start_char: 7,
    end_char: 11,
    size: 5,
    field: 'Type Group ID',
    description: 'Group Header',
  },
  {
    version: '21',
    line: '2',
    group_name: 'GRH',
    input_type: 'alpha',
    is_required: true,
    tag: 'free_text',
    start_char: 12,
    end_char: 16,
    size: 5,
    field: 'Version Number for this transaction ty',
    description: 'Group Header',
  },
  {
    version: '21',
    line: '2',
    group_name: 'GRH',
    input_type: 'numeric',
    is_required: true,
    tag: 'free_text',
    start_char: 17,
    end_char: 26,
    size: 10,
    field: 'Batch Request',
    description: 'Group Header',
  },
  {
    version: '21',
    line: '2',
    group_name: 'GRH',
    input_type: 'lookup',
    is_required: true,
    tag: 'free_text',
    start_char: 27,
    end_char: 28,
    size: 2,
    field: 'Submission / Distribution type',
    description: 'Group Header',
  },

  {
    version: '21',
    line: '-2',
    group_name: 'GRT',
    input_type: 'lookup',
    is_required: true,
    tag: 'GRT',
    start_char: 1,
    end_char: 3,
    size: 3,
    field: 'Record Type',
    description: 'Group Trailer',
  },
  {
    version: '21',
    line: '-2',
    group_name: 'GRT',
    input_type: 'numeric',
    is_required: true,
    tag: 'free_text',
    start_char: 4,
    end_char: 8,
    size: 5,
    field: 'Group ID',
    description: 'Group Trailer',
  },
  {
    version: '21',
    line: '-2',
    group_name: 'GRT',
    input_type: 'numeric',
    is_required: true,
    tag: 'free_text',
    start_char: 9,
    end_char: 16,
    size: 8,
    field: 'Transaction Count',
    description: 'Group Trailer',
  },
  {
    version: '21',
    line: '-2',
    group_name: 'GRT',
    input_type: 'numeric',
    is_required: true,
    tag: 'free_text',
    start_char: 17,
    end_char: 24,
    size: 8,
    field: 'Record Count',
    description: 'Group Trailer',
  },

  {
    version: '21',
    line: '-1',
    group_name: 'GRT',
    input_type: 'lookup',
    is_required: true,
    tag: 'GRT',
    start_char: 1,
    end_char: 3,
    size: 3,
    field: 'Record Type',
    description: 'Transmission Trailer',
  },
  {
    version: '21',
    line: '-1',
    group_name: 'GRT',
    input_type: 'numeric',
    is_required: true,
    tag: 'free_text',
    start_char: 4,
    end_char: 8,
    size: 5,
    field: 'Group ID',
    description: 'Transmission Trailer',
  },
  {
    version: '21',
    line: '-1',
    group_name: 'GRT',
    input_type: 'numeric',
    is_required: true,
    tag: 'free_text',
    start_char: 9,
    end_char: 16,
    size: 8,
    field: 'Transaction Count',
    description: 'Transmission Trailer',
  },
  {
    version: '21',
    line: '-1',
    group_name: 'GRT',
    input_type: 'numeric',
    is_required: true,
    tag: 'free_text',
    start_char: 17,
    end_char: 24,
    size: 8,
    field: 'Record Count',
    description: 'Transmission Trailer',
  },
];
